Update block_merge.yaml

diff --git a/.github/workflows/block_merge.yaml b/.github/workflows/block_merge.yaml
--- a/.github/workflows/block_merge.yaml
+++ b/.github/workflows/block_merge.yaml
@@ -10,7 +10,7 @@ on:
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.issue.number }}
   cancel-in-progress: true
-  
+
 jobs:
   check-shortcut-link:
     runs-on: ubuntu-latest
@@ -28,43 +28,34 @@ jobs:
           PR_NUMBER=${{ github.event.pull_request.number }}
           echo "PR Number: $PR_NUMBER"
           echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
-      - name: Reset PR Checks
-        run: |
-          # Get the current HEAD of the PR branch
-          PR_HEAD=$(curl -s -H "Authorization: token $TOKEN" \
-          "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER" \
-          | jq -r .head.sha)
           
-          # Get the PR branch name
-          PR_BRANCH=$(curl -s -H "Authorization: token $TOKEN" \
-          "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER" \
-          | jq -r .head.ref)
-
-          echo "Using PR HEAD SHA: $PR_HEAD"
-          # Create a new empty commit
-          EMPTY_COMMIT=$(curl -s -X POST -H "Authorization: token $TOKEN" \
-          -H "Accept: application/vnd.github.v3+json" \
-          "https://api.github.com/repos/$REPO/git/commits" \
-          -d '{
-           "message": "Reset checks",
-           "tree": "$PR_HEAD",
-           "parents": ["$PR_HEAD"]
-          }' | jq -r .sha)
-          echo "Created Empty Commit SHA: $EMPTY_COMMIT"
-
-
-          # Update the reference of the PR branch
-          curl -s -X PATCH -H "Authorization: token $TOKEN" \
-          -H "Accept: application/vnd.github.v3+json" \
-          "https://api.github.com/repos/$REPO/git/refs/heads/$PR_BRANCH"\
-          -d '{
-          "sha": "'"$EMPTY_COMMIT"'",
-          "force": true
-          }'
-
-          echo "PR checks have been reset."      
-          echo "PR_SHA=$EMPTY_COMMIT" >> $GITHUB_ENV
- 
+      - name: Get PR SHA and List Old Check Runs
+        id: get_sha_and_check_runs
+        run: |
+          echo "$PR_NUMBER"
+          PR_SHA=$(curl -s -H "Authorization: token $TOKEN" \
+              "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER" | jq -r .head.sha)
+          echo "Using PR SHA: $PR_SHA" # Debug
+          
+          CHECK_RUNS=$(curl -s -H "Authorization: token $TOKEN" \
+            "https://api.github.com/repos/${REPO}/commits/${PR_SHA}/check-runs")
+          
+          OLD_CHECK_RUN_IDS=$(echo "$CHECK_RUNS" | jq -r '.check_runs[] | select(.name == "check-shortcut-link") | .id')
+          echo "Old Check Run IDs:"
+          echo "$OLD_CHECK_RUN_IDS"
+          echo "old_check_run_ids=$OLD_CHECK_RUN_IDS" >> $GITHUB_OUTPUT
+          echo "pr_sha=$PR_SHA" >> $GITHUB_OUTPUT
+      - name: Delete Old Check Runs
+        if: steps.get_sha_and_check_runs.outputs.old_check_run_ids != ''
+        run: |
+          IDS=$(echo '${{ steps.get_sha_and_check_runs.outputs.old_check_run_ids }}' | jq -r '.[]')
+          for CHECK_RUN_ID in ${IDS}; do
+            echo "Deleting Check Run ID: $CHECK_RUN_ID"
+            curl -X DELETE \
+              -H "Authorization: token $TOKEN" \
+              -H "Accept: application/vnd.github.v3+json" \
+              "https://api.github.com/repos/${REPO}/check-runs/$CHECK_RUN_ID"
+          done
       - name: Get PR Details
         id: get_pr_details
         run: |
@@ -94,12 +85,10 @@ jobs:
           while :; do
             RESPONSE=$(curl -s -H "Authorization: token $TOKEN" \
               "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments?per_page=$PER_PAGE&page=$PAGE")
-
             # Break if no more comments are returned
             if [[ $(echo "$RESPONSE" | jq '. | length') -eq 0 ]]; then
               break
             fi
-
             COMMENTS+="$RESPONSE"
             ((PAGE++))
           done
@@ -113,7 +102,25 @@ jobs:
             echo "This PR does not have a linked Shortcut story."
             echo "status=failure" >> $GITHUB_OUTPUT
           fi
+      - name: Update Check Run Status
+        if: steps.get_sha_and_check_runs.outputs.old_check_run_id != 'null' && steps.get_sha_and_check_runs.outputs.old_check_run_id != ''
+        run: |
+          CHECK_RUN_UPDATE_URL="https://api.github.com/repos/${REPO}/check-runs/${{ steps.get_sha_and_check_runs.outputs.old_check_run_id }}"
+          curl -X PATCH \
+            -H "Authorization: token $TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            "$CHECK_RUN_UPDATE_URL" \
+            -d '{
+              "status": "completed",
+              "conclusion": "'"${{ steps.get_comments_and_verify.outputs.status }}"'"
+            }'
+          # Exit with failure if status is failure
+          if [[ "${{ steps.get_comments_and_verify.outputs.status }}" == 'failure' ]]; then
+            echo "This PR does not have a linked Shortcut story."
+            exit 1
+          fi
       - name: Create Check Run
+        if: steps.get_sha_and_check_runs.outputs.old_check_run_id == 'null' || steps.get_sha_and_check_runs.outputs.old_check_run_id == ''
         run: |
           CHECK_RUN_CREATE_URL="https://api.github.com/repos/${REPO}/check-runs"
           curl -X POST \
@@ -122,7 +129,8 @@ jobs:
             "$CHECK_RUN_CREATE_URL" \
             -d '{
               "name": "check-shortcut-link",
-              "head_sha": "'"${PR_SHA}"'",
+              "head_sha": "'"${{ steps.get_sha_and_check_runs.outputs.pr_sha }}"'",
+              "head_sha": "'"${{ steps.get_sha_and_check_runs.outputs.pr_sha }}"'",
               "status": "completed",
               "conclusion": "'"${{ steps.get_comments_and_verify.outputs.status }}"'",
               "output": {
